//! Loadable keyed store fields.
//!
//! Combines loading state with keyed reactivity for collections.
//! This allows you to:
//! - Track loading/error state for async collection fetches
//! - Get keyed iteration when data is ready
//! - Maintain stable keys across re-renders

use crate::{
    keyed::KeyedSubfield,
    loadable::Loadable,
    store_field::StoreField,
    Subfield,
};
use reactive_graph::traits::{DefinedAt, IsDisposed, Track};
use std::{
    error::Error,
    fmt::Debug,
    hash::Hash,
    ops::IndexMut,
    panic::Location,
};

/// A loadable field with keyed collection support.
///
/// This type combines loading state management with keyed reactivity:
/// - State tracking: `NotStarted`, `Loading`, `Ready`, `Failed`
/// - Keyed iteration when data is ready
///
/// The actual struct in the store has two fields generated by the macro:
/// - `{name}_state: Loadable<(), E>` - The loading state
/// - `{name}: T` (typically `Vec<Item>`) with `#[store(key: K = ...)]` - The keyed data
///
/// # Type Parameters
///
/// - `StateInner` - The inner store field type for state
/// - `DataInner` - The inner store field type for data
/// - `Prev` - The parent struct type
/// - `K` - The key type for keyed access
/// - `T` - The collection type (e.g., `Vec<Item>`)
/// - `E` - The error type (must implement `std::error::Error`)
///
/// # Example
///
/// ```rust,ignore
/// #[derive(Store)]
/// struct State {
///     #[store(loadable, key: IdType<Item> = |item| item.id)]
///     items: Vec<Item>,  // Returns LoadableKeyedSubfield
/// }
///
/// // Usage:
/// state.items().set_loading();
///
/// // Write data and set ready
/// *state.items().data_write().write() = fetched_items;
/// state.items().set_ready();
///
/// // Access when ready
/// state.items().with(
///     || view! { "Not loaded" },
///     || view! { "Loading..." },
///     |data| view! {
///         <For
///             each=move || data.clone()
///             key=|item| item.id
///             children=|item| view! { <ItemRow item=item /> }
///         />
///     },
///     |err| view! { "Error: " {err} },
/// );
/// ```
#[derive(Clone, Copy)]
pub struct LoadableKeyedSubfield<StateInner, DataInner, Prev, K, T, E>
where
    StateInner: StoreField<Value = Prev>,
    DataInner: StoreField<Value = Prev>,
    for<'a> &'a T: IntoIterator,
    T: IndexMut<usize>,
    K: Hash + PartialEq + Eq,
    E: Error,
{
    #[cfg(any(debug_assertions, leptos_debuginfo))]
    defined_at: &'static Location<'static>,
    state: Subfield<StateInner, Prev, Loadable<(), E>>,
    data: KeyedSubfield<DataInner, Prev, K, T>,
}

impl<StateInner, DataInner, Prev, K, T, E>
    LoadableKeyedSubfield<StateInner, DataInner, Prev, K, T, E>
where
    StateInner: StoreField<Value = Prev>,
    DataInner: StoreField<Value = Prev>,
    Prev: 'static,
    for<'a> &'a T: IntoIterator,
    T: IndexMut<usize>,
    K: Debug + Send + Sync + Hash + PartialEq + Eq + Clone + 'static,
    E: Error + Clone + 'static,
{
    /// Creates a new loadable keyed subfield.
    #[track_caller]
    pub fn new(
        state: Subfield<StateInner, Prev, Loadable<(), E>>,
        data: KeyedSubfield<DataInner, Prev, K, T>,
    ) -> Self {
        Self {
            #[cfg(any(debug_assertions, leptos_debuginfo))]
            defined_at: Location::caller(),
            state,
            data,
        }
    }

    /// Returns `true` if loading has not started.
    pub fn is_not_started(&self) -> bool {
        self.state
            .reader()
            .map(|r| r.is_not_started())
            .unwrap_or(true)
    }

    /// Returns `true` if currently loading.
    pub fn is_loading(&self) -> bool {
        self.state
            .reader()
            .map(|r| r.is_loading())
            .unwrap_or(false)
    }

    /// Returns `true` if data is ready.
    pub fn is_ready(&self) -> bool {
        self.state.reader().map(|r| r.is_ready()).unwrap_or(false)
    }

    /// Returns `true` if loading failed.
    pub fn is_failed(&self) -> bool {
        self.state.reader().map(|r| r.is_failed()).unwrap_or(false)
    }

    /// Get the error if failed.
    ///
    /// This is reactive - it will track the state field.
    pub fn error(&self) -> Option<E> {
        self.state.track_field();
        self.state.reader().and_then(|r| match &*r {
            Loadable::Failed(e) => Some(e.clone()),
            _ => None,
        })
    }

    /// Get the error if failed, without tracking.
    pub fn error_untracked(&self) -> Option<E> {
        self.state.reader().and_then(|r| match &*r {
            Loadable::Failed(e) => Some(e.clone()),
            _ => None,
        })
    }

    /// Set to `Loading` state.
    pub fn set_loading(&self) {
        if let Some(mut w) = self.state.writer() {
            *w = Loadable::Loading;
        }
    }

    /// Set to `Ready` state.
    ///
    /// Call this after updating the data via `data_write()`.
    pub fn set_ready(&self) {
        if let Some(mut w) = self.state.writer() {
            *w = Loadable::Ready(());
        }
    }

    /// Set to `Failed` with the given error.
    pub fn set_failed(&self, error: E) {
        if let Some(mut w) = self.state.writer() {
            *w = Loadable::Failed(error);
        }
    }

    /// Reset to `NotStarted` state.
    pub fn reset(&self) {
        if let Some(mut w) = self.state.writer() {
            *w = Loadable::NotStarted;
        }
    }

    /// Get read access to the underlying keyed data.
    ///
    /// Returns `None` if not ready or disposed.
    /// This is useful for reading data only when it's available.
    pub fn data(&self) -> Option<KeyedSubfield<DataInner, Prev, K, T>>
    where
        DataInner: Clone,
    {
        if self.is_ready() {
            Some(self.data.clone())
        } else {
            None
        }
    }

    /// Get write access to the underlying keyed data.
    ///
    /// This allows writing even when not in ready state,
    /// which is necessary for initial data population.
    ///
    /// Typical usage pattern:
    /// ```rust,ignore
    /// state.items().set_loading();
    /// // ... fetch data ...
    /// *state.items().data_write().write() = fetched_items;
    /// state.items().set_ready();
    /// ```
    pub fn data_write(&self) -> KeyedSubfield<DataInner, Prev, K, T>
    where
        DataInner: Clone,
    {
        self.data.clone()
    }

    /// Track this field for reactivity.
    ///
    /// Tracks both the state and data fields.
    pub fn track(&self)
    where
        DataInner: Clone,
    {
        self.state.track_field();
        self.data.track_field();
    }

    /// Track only the state field.
    ///
    /// Use this when you only need to react to loading state changes,
    /// not data changes.
    pub fn track_state(&self) {
        self.state.track_field();
    }

    /// Track only the data field.
    ///
    /// Use this when you know data is ready and only want to
    /// react to data changes.
    pub fn track_data(&self)
    where
        DataInner: Clone,
    {
        self.data.track_field();
    }

    /// Match on the loadable state with closures.
    ///
    /// This is the primary way to reactively render based on loading state.
    /// The `ready` closure receives the keyed subfield for iteration.
    ///
    /// # Example
    ///
    /// ```rust,ignore
    /// state.items().with(
    ///     || view! { "Click to load" },
    ///     || view! { <Spinner /> },
    ///     |items| view! {
    ///         <For
    ///             each=move || items.clone()
    ///             key=|item| item.id().get()
    ///             children=|item| view! { <ItemRow item=item /> }
    ///         />
    ///     },
    ///     |error| view! { <ErrorBanner message=error.to_string() /> },
    /// )
    /// ```
    pub fn with<R>(
        &self,
        not_started: impl FnOnce() -> R,
        loading: impl FnOnce() -> R,
        ready: impl FnOnce(KeyedSubfield<DataInner, Prev, K, T>) -> R,
        failed: impl FnOnce(&E) -> R,
    ) -> R
    where
        DataInner: Clone,
    {
        self.state.track_field();
        match self.state.reader().as_deref() {
            Some(Loadable::NotStarted) | None => not_started(),
            Some(Loadable::Loading) => loading(),
            Some(Loadable::Ready(())) => ready(self.data.clone()),
            Some(Loadable::Failed(e)) => failed(e),
        }
    }

    /// Similar to `with`, but also provides the data in non-ready states.
    ///
    /// This is useful when you want to show stale data while loading,
    /// or show data alongside error messages.
    pub fn with_data<R>(
        &self,
        not_started: impl FnOnce(KeyedSubfield<DataInner, Prev, K, T>) -> R,
        loading: impl FnOnce(KeyedSubfield<DataInner, Prev, K, T>) -> R,
        ready: impl FnOnce(KeyedSubfield<DataInner, Prev, K, T>) -> R,
        failed: impl FnOnce(&E, KeyedSubfield<DataInner, Prev, K, T>) -> R,
    ) -> R
    where
        DataInner: Clone,
    {
        self.state.track_field();
        let data = self.data.clone();
        match self.state.reader().as_deref() {
            Some(Loadable::NotStarted) | None => not_started(data),
            Some(Loadable::Loading) => loading(data),
            Some(Loadable::Ready(())) => ready(data),
            Some(Loadable::Failed(e)) => failed(e, data),
        }
    }
}

impl<StateInner, DataInner, Prev, K, T, E> DefinedAt
    for LoadableKeyedSubfield<StateInner, DataInner, Prev, K, T, E>
where
    StateInner: StoreField<Value = Prev>,
    DataInner: StoreField<Value = Prev>,
    for<'a> &'a T: IntoIterator,
    T: IndexMut<usize>,
    K: Hash + PartialEq + Eq,
    E: Error,
{
    fn defined_at(&self) -> Option<&'static Location<'static>> {
        #[cfg(any(debug_assertions, leptos_debuginfo))]
        {
            Some(self.defined_at)
        }
        #[cfg(not(any(debug_assertions, leptos_debuginfo)))]
        {
            None
        }
    }
}

impl<StateInner, DataInner, Prev, K, T, E> IsDisposed
    for LoadableKeyedSubfield<StateInner, DataInner, Prev, K, T, E>
where
    StateInner: StoreField<Value = Prev> + IsDisposed,
    DataInner: StoreField<Value = Prev>,
    for<'a> &'a T: IntoIterator,
    T: IndexMut<usize>,
    K: Hash + PartialEq + Eq,
    E: Error,
{
    fn is_disposed(&self) -> bool {
        self.state.is_disposed()
    }
}

impl<StateInner, DataInner, Prev, K, T, E> Track
    for LoadableKeyedSubfield<StateInner, DataInner, Prev, K, T, E>
where
    StateInner: StoreField<Value = Prev> + Track + 'static,
    DataInner: StoreField<Value = Prev> + Track + Clone + 'static,
    Prev: 'static,
    for<'a> &'a T: IntoIterator,
    T: IndexMut<usize> + 'static,
    K: Debug + Send + Sync + Hash + PartialEq + Eq + Clone + 'static,
    E: Error + 'static,
{
    fn track(&self) {
        self.state.track();
        self.data.track();
    }
}

impl<StateInner, DataInner, Prev, K, T, E> std::fmt::Debug
    for LoadableKeyedSubfield<StateInner, DataInner, Prev, K, T, E>
where
    StateInner: StoreField<Value = Prev>,
    DataInner: StoreField<Value = Prev>,
    Prev: 'static,
    for<'a> &'a T: IntoIterator,
    T: IndexMut<usize>,
    K: Debug + Send + Sync + Hash + PartialEq + Eq + Clone + 'static,
    E: Error + Clone + 'static,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("LoadableKeyedSubfield")
            .field(
                "state",
                &self.state.reader().map(|r| match &*r {
                    Loadable::NotStarted => "NotStarted",
                    Loadable::Loading => "Loading",
                    Loadable::Ready(_) => "Ready",
                    Loadable::Failed(_) => "Failed(...)",
                }),
            )
            .finish()
    }
}
